#!/bin/bash
clear

url_checker() {
    if [ ! "${1//:*}" = http ]; then
        if [ ! "${1//:*}" = https ]; then
            echo -e "\e[31m[!] Invalid URL. Please use http or https.\e[0m"
            exit 1
        fi
    fi
}

figlet -f small "Anonym-R"
printf "\e[1;32m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
printf "\e[1;32m║ \e[1;37mAUTHOR  : Anonym-R             \e[1;32m║     \n"
printf "\e[1;32m║ \e[1;97mWebSite : https://anonym-r.ga  \e[1;32m║ \n"
printf "\e[1;32m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\e[0m"
echo ""
echo -e " \e[1;96m>>\e[0m Phishing URL Generate:\n"
echo -n "Paste Phishing URL here (with http or https): "
read phish
url_checker $phish
sleep 1
echo "Processing and Modifing Phishing URL"
echo ""
short=$(curl -s https://is.gd/create.php\?format\=simple\&url\=${phish})
shorter=${short#https://}
echo 'Domain to mask the Phishing URL (with http or https), ex: https://google.com, http
://anything.org) :'
echo -en "\e[32m=>\e[0m "
read mask
url_checker $mask
echo -e '\nType social engineering words:(like free-money, best-pubg-tricks)'
echo -e "\e[31mDon't use space just use '-' between social engineering words\e[0m"
echo -en "\e[32m=>\e[0m "
read words
if [[ -z "$words" ]]; then
echo -e "\e[31m[!] No words.\e[0m"
echo -e "\nGenerating Link...\n"
final=$mask@$shorter
echo -e "Here is the URL:\e[32m ${final} \e[0m\n"
exit
fi
if [[ "$words" =~ " " ]]; then
echo -e "\e[31m[!] Invalid words. Please avoid space.\e[0m"
echo -e "\nGenerating Link...\n"
final=$mask@$shorter
echo -e "Here is the URL:\e[32m ${final} \e[0m\n"
exit
fi
echo -e "\nGenerating Link...\n"
final=$mask-$words@$shorter
echo -e "Here is the URL:\e[32m ${final} \e[0m\n"
